#!/usr/bin/env python3
"""El pedido ORIGINAL de William sobrevive la compactación (idea 5 de Bob, tarea 1699).

QUÉ PROTEGE, y por qué el filtro es el test y no un detalle:
La compactación conserva lo RECIENTE. En una tarea larga eso alcanza para seguir
trabajando pero no para recordar PARA QUÉ se empezó. Este rescate lee el primer
turno HUMANO del transcript. El riesgo real no es no encontrarlo: es encontrar
basura y guardarla igual — el eco de un `/model`, la salida de un comando local,
un recordatorio del sistema o el resultado de una herramienta. Ahí el objetivo se
pierde lo mismo, con el agravante de que el estado guardado PARECE correcto.

POR QUÉ SE LEE EL TRANSCRIPT Y NO EL `sessionContext` DEL HOOK:
`pre_compact_hook.py` pedía sessionContext/summary/compact_summary y el harness no
entrega ninguna. Medido el 4-sep-2026 sobre el último estado real guardado (3-sep
21:47): decisions, corrections y tasks_in_progress vacíos, technical_state vacío,
mientras los campos que venían de la DB sí tenían contenido. El harness entrega
`transcript_path`.

Owner: ADA — 4-sep-2026.
"""
from __future__ import annotations

import json
import importlib.util
import io
import sys
import unittest
from pathlib import Path
from unittest.mock import patch

# El sujeto se puede redirigir para mutar una COPIA y no el árbol vivo.
import os
sys.path.insert(0, os.environ.get("SEAL_COMPACT_MODULE_DIR",
                                  str(Path(__file__).resolve().parents[1])))

from compact_original_request import extract_original_request, is_human_turn  # noqa: E402


def write_transcript(tmp: Path, rows: list[dict]) -> Path:
    path = tmp / "transcript.jsonl"
    path.write_text("\n".join(json.dumps(r) for r in rows) + "\n", encoding="utf-8")
    return path


HUMANO = {"type": "user", "message": {"role": "user",
          "content": [{"type": "text", "text": "ADA, arregla el candado y no toques el resto"}]}}


def load_pre_compact_hook():
    """Carga el hook exacto que el arnés/revisor señale, no una copia fija."""
    default = Path(__file__).resolve().parents[1] / "pre_compact_hook.py"
    path = Path(os.environ.get("SEAL_PRE_COMPACT_HOOK_PATH", str(default)))
    spec = importlib.util.spec_from_file_location("_pre_compact_hook_under_test", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"no pude cargar el hook bajo prueba: {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class RescateDelPedidoOriginal(unittest.TestCase):
    def setUp(self):
        import tempfile
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = Path(self._tmp.name)

    def tearDown(self):
        self._tmp.cleanup()

    def test_gana_el_primer_turno_humano_no_el_primero_a_secas(self):
        """Cinco renglones de ruido antes del pedido: debe saltarlos todos."""
        ruido = [
            {"type": "system", "message": {"content": "boot"}},
            {"type": "user", "message": {"role": "user",
             "content": "<local-command-caveat>Caveat: The messages below were generated by the user</local-command-caveat>"}},
            {"type": "user", "message": {"role": "user", "content": "<command-name>/model</command-name>"}},
            {"type": "user", "isMeta": True, "message": {"role": "user", "content": "meta"}},
            {"type": "user", "message": {"role": "user",
             "content": [{"type": "tool_result", "content": "salida de herramienta"}]}},
        ]
        path = write_transcript(self.tmp, ruido + [HUMANO,
                {"type": "user", "message": {"role": "user", "content": "posterior, no debe ganar"}}])
        self.assertEqual(extract_original_request(path),
                         "ADA, arregla el candado y no toques el resto")

    def test_un_mensaje_posterior_no_desplaza_al_original(self):
        path = write_transcript(self.tmp, [
            HUMANO,
            {"type": "user", "message": {"role": "user", "content": "y ahora hacé otra cosa"}},
            {"type": "user", "message": {"role": "user", "content": "y otra más"}},
        ])
        self.assertEqual(extract_original_request(path),
                         "ADA, arregla el candado y no toques el resto")

    def test_recordatorio_del_sistema_y_notificacion_no_son_el_usuario(self):
        for texto in ("<system-reminder>algo</system-reminder>",
                      "<task-notification>evento</task-notification>",
                      "[AUTO-BOOT POST-COMPACTACIÓN] hacé el boot",
                      "[SOUL Active Recall — ADA, 189ms] correcciones"):
            with self.subTest(texto=texto[:28]):
                path = write_transcript(self.tmp, [
                    {"type": "user", "message": {"role": "user", "content": texto}}, HUMANO])
                self.assertEqual(extract_original_request(path),
                                 "ADA, arregla el candado y no toques el resto")

    def test_un_tool_result_con_texto_al_lado_no_es_una_peticion(self):
        """Lo cazó un mutante: mi primera versión de este test no probaba nada.

        El renglón de tool_result que usaba traía SÓLO el bloque tool_result, sin
        texto, así que lo rechazaba la guarda de 'texto vacío' y la exclusión real
        nunca se ejercitaba. Un mutante que aceptaba tool_result SOBREVIVIÓ. La
        forma que importa es la mixta: el harness manda el resultado de la
        herramienta con texto al lado, y eso NO es una petición del usuario.
        """
        mixto = {"type": "user", "message": {"role": "user", "content": [
            {"type": "tool_result", "content": "salida"},
            {"type": "text", "text": "esto vino pegado al resultado, no lo escribió William"},
        ]}}
        self.assertFalse(is_human_turn(mixto), "un tool_result con texto al lado no es una petición")
        path = write_transcript(self.tmp, [mixto, HUMANO])
        self.assertEqual(extract_original_request(path),
                         "ADA, arregla el candado y no toques el resto")

    def test_sin_turno_humano_devuelve_None_en_vez_de_basura(self):
        """Preferimos vacío antes que guardar ruido que parece un objetivo."""
        path = write_transcript(self.tmp, [
            {"type": "assistant", "message": {"role": "assistant", "content": "hola"}},
            {"type": "user", "message": {"role": "user", "content": "<command-name>/clear</command-name>"}},
        ])
        self.assertIsNone(extract_original_request(path))

    def test_entrada_rota_no_tumba_la_compactacion(self):
        """Un transcript corrupto o ausente no puede romper el hook."""
        self.assertIsNone(extract_original_request(None))
        self.assertIsNone(extract_original_request(self.tmp / "no_existe.jsonl"))
        rota = self.tmp / "rota.jsonl"
        rota.write_text("{no es json\n\n{\"type\":\"user\"}\n", encoding="utf-8")
        self.assertIsNone(extract_original_request(rota))
        mixta = self.tmp / "mixta.jsonl"
        mixta.write_text("{basura\n" + json.dumps(HUMANO) + "\n", encoding="utf-8")
        self.assertEqual(extract_original_request(mixta),
                         "ADA, arregla el candado y no toques el resto")

    def test_se_recorta_para_no_inflar_el_estado(self):
        largo = {"type": "user", "message": {"role": "user", "content": "x" * 9_000}}
        path = write_transcript(self.tmp, [largo])
        self.assertEqual(len(extract_original_request(path)), 2_000)

    def test_control_el_filtro_no_rechaza_todo(self):
        """CONTROL de no-vacuidad: si `is_human_turn` dijera siempre False, todos los
        casos de arriba pasarían por la razón equivocada. Acá se exige que SÍ acepte
        un turno humano legítimo y que SÍ rechace uno que no lo es."""
        self.assertTrue(is_human_turn(HUMANO), "rechaza un turno humano legítimo: filtro inútil")
        self.assertTrue(is_human_turn({"type": "user", "message": {"role": "user", "content": "hola"}}))
        self.assertFalse(is_human_turn({"type": "assistant", "message": {"content": "hola"}}))
        self.assertFalse(is_human_turn({"type": "user", "message": {"role": "user", "content": "   "}}))

    def test_main_cablea_transcript_path_y_no_sessionContext_al_pedido_original(self):
        """Protege la costura que faltaba: la función correcta debe ejecutarse con la clave correcta.

        `sessionContext` sigue siendo una entrada válida para el resumen reciente. El pedido
        original, en cambio, tiene que salir del transcript. Los dos valores deliberadamente
        distintos matan tanto el regreso a la clave vieja como un hook que no cablee el
        extractor aunque éste funcione perfecto por separado.
        """
        transcript = write_transcript(self.tmp, [HUMANO])
        resumen_reciente = "RESUMEN RECIENTE: no es el pedido original de William"
        vistos = {}

        hook = load_pre_compact_hook()

        async def guardar_sin_db(contexto, pedido_original):
            vistos["contexto"] = contexto
            vistos["pedido_original"] = pedido_original
            return "guardado por doble de prueba"

        hook.save_pre_compact_state = guardar_sin_db
        entrada = json.dumps({
            "sessionContext": resumen_reciente,
            "transcript_path": str(transcript),
        })
        salida = io.StringIO()
        with patch.object(sys, "stdin", io.StringIO(entrada)), patch.object(sys, "stdout", salida):
            hook.main()

        self.assertEqual(vistos["contexto"], resumen_reciente)
        self.assertEqual(vistos["pedido_original"],
                         "ADA, arregla el candado y no toques el resto")
        self.assertEqual(json.loads(salida.getvalue()), {
            "systemMessage": "guardado por doble de prueba",
            "continue": True,
        })


if __name__ == "__main__":
    unittest.main(verbosity=2)
